### ISSUE TITLE
[FEAT] Rename projects and rearrange rows

### ISSUE THREAD

**Issue by emptystudent** [EmbeddedLLM/JamAIBase#10]
### Is your feature request related to a problem? Please describe.

I can not rename the projects and I can not move the rows to rearrange them. we can rearrange columns in the action table but now rows?

### Describe the solution you'd like

allow to rename projects and also allow to move and rearrange rows like in excel

**Comment by jiahuei** [comment]
Hello @emptystudent , thanks for the suggestion!
We have project rename in our roadmap.
On the other hand, what's the use case for row rearrangement? For now we are targeting DB use cases.

**Comment by emptystudent** [comment]
row arrangement can help in 

1. help rank responses by the user after the project is complete or rearrange responses for better presentation based on user needs.

2. The functionality already exists to rearrange columns logically rearranging rows can be a nice feature too!.

**Comment by jiahuei** [comment]
- Project rename has been implemented
- Row ordering is not being considered at the moment, since our table is meant to be a DB table rather than a spreadsheet
