### ISSUE TITLE
[BUG] UI not responding without refresh in the billing section

### ISSUE THREAD

**Issue by emptystudent** [EmbeddedLLM/JamAIBase#11]
https://github.com/EmbeddedLLM/JamAIBase/assets/27153722/c66b4feb-65fd-4d23-9bd2-69a363c21247

The URL changes but UI no response

**Comment by jiahuei** [comment]
Hi @emptystudent , is this still an issue for you? It should be fixed by now

**Comment by jiahuei** [comment]
Closing as it should be fixed
