### ISSUE TITLE
[BUG] Integration with Grammarly

### ISSUE THREAD

**Issue by emptystudent** [EmbeddedLLM/JamAIBase#12]
### Describe the bug

When I edit text with Grammarly, the text gets edited, but the column modification is nullified.

https://github.com/EmbeddedLLM/JamAIBase/assets/27153722/ca979ea8-d021-4eaa-8417-88e6a5085d7c

**Comment by jiahuei** [comment]
hello @emptystudent , cell value edit must be committed by hitting Enter

**Comment by jiahuei** [comment]
Closed for inactivity
