### ISSUE TITLE
[FEAT] Add negative prompt column input field to system prompt

### ISSUE THREAD

**Issue by szeyu** [EmbeddedLLM/JamAIBase#13]
### Is your feature request related to a problem? Please describe.
I always wanna rewrite the statement to told the system what is the restriction of output. 

### Describe the solution you'd like
I would prefer if there is a negative prompt column input field to system prompt, where the users will input what is the incorrect example of output

### Describe alternatives you've considered
negative prompt can be written in system prompt with some statement of these outputs are incorrect

### Additional context
if you check stable diffusion and DaVinci solution, they provide a field to input negative prompt which is the restriction of output

**Comment by jiahuei** [comment]
hello @szeyu , I'm not sure I fully understand your suggestion. Negative prompts are an inherent feature of stable diffusion models, but it is not the case for LLMs. Can you find examples of negative prompts for LLMs?

**Comment by jiahuei** [comment]
Closing for now
