### ISSUE TITLE
Credit tracking

### ISSUE THREAD

**Issue by emptystudent** [EmbeddedLLM/JamAIBase#7]
I am trying to make a new chat agent but it says my credits are insufficient there is no way to know how and when they got used up. how do I track my spending? billing only shows the balance, not the track record, to understand the credit usage.

![crd](https://github.com/EmbeddedLLM/JamAIBase/assets/27153722/98cab90a-b36c-49f2-9e86-bf9dc60d974f)

**Comment by jiahuei** [comment]
Hi @emptystudent , this issue should be partially fixed with the latest update. Now you should see exactly what type of quota has ran out in the error message, although we still don't have usage tracking other than LLM tokens.
